### PR TITLE
implemented username/password auth, sign out, change password and not logged in reminder features.

### PR DESCRIPTION
**Pull request by Kishore-Elangovan**
- https://trello.com/c/dVj9taf7/36-username-or-another-platform-auth
- https://trello.com/c/DquFzFkN/106-sign-out
- https://trello.com/c/4gvdVmAL/39-change-password
- https://trello.com/c/69jdy6pu/54-not-logged-in-reminder

### CODE REVIEW

**Comment by gregk-amr** [comment]
can you please update, fixing any conflicts found here ?

**Comment by gregk-amr** [comment]
does this PR need to be closed? was it resolved in another PR? Seems conflict still showing

**Comment by KishoreElan** [comment]
> does this PR need to be closed? was it resolved in another PR? Seems conflict still showing

@gregk-amr we fixed the conflicts. Please take a look and merge.

**Comment by gregk-amr** [comment]
👌

**Pull request merged**
