### PR TITLE
Sprint2 - Add Research

### PR DESCRIPTION
**Pull request by Vemahk**
Added vue-multiselect for multiselect dropdowns used on the upload page.
Added in mock API calls for any future API work we do. I did create an API for the website to talk to in ASP.NET Core, but it is not included in the base repository. We can look into including it later if we want to, or making its own repository.
Added Publications table on the user profile page for viewing a list of uploaded publications.
The DOI link in the Publications Table on the Profile page works as a link, so if a valid doi.org address is given, then it will route to the original publication page.

### CODE REVIEW

**Comment by qeleb** [comment]
this is excellent work honestly. i’ll merge this very soon

**Comment by gregk-amr** [comment]
this has a conflict in the settings page, please resolve and update this request

**Comment by gregk-amr** [comment]
There is a conflict with package.json, please resolve

**Review by qeleb — COMMENTED** [review]
Great work

**Comment by qeleb** [comment]
I think this ought to be merged

**Pull request merged**
