### PR TITLE
sprint2 krishna kishore social network

### PR DESCRIPTION
**Pull request by KishoreElan**

### CODE REVIEW

**Comment by gregk-amr** [comment]
could we get a link to the trello card(s) this story is for in this chat?

**Comment by kvb160230** [comment]
Stories Completed - 
https://trello.com/c/G9qPPVay/63-suggested-people-list
https://trello.com/c/NnWXZPc5/120-not-logged-in-reminder
https://trello.com/c/XkSebAV0/113-follow-other-registered-users
https://trello.com/c/LWWM4Nu7/46-unfollow-other-registered-users
https://trello.com/c/SOovmLeU/40-add-remove-colleagues-to-my-network

**Comment by kvb160230** [comment]
> could we get a link to the trello card(s) this story is for in this chat?

@gregk-amr Done 👍

**Comment by gregk-amr** [comment]
This branch has conflicts, please resolve and update before I will merge this

**Comment by KishoreElan** [comment]
@gregk-amr resolved conflicts. You can merge now.

**Pull request merged**
